name: paths_management_platzi
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - appdirs=1.4.4
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - attrs=20.2.0
  - backcall=0.2.0
  - bleach=3.2.1
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=3.0.4
  - cryptography=3.4.7
  - debugpy=1.3.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - fs=2.4.11
  - icu=58.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - ipykernel=6.0.1
  - ipython=7.25.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.18.0
  - jinja2=2.11.2
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.1
  - jupyterlab=2.2.6
  - jupyterlab_server=1.2.0
  - libcxx=12.0.1
  - libffi=3.3
  - libpng=1.6.37
  - libsodium=1.0.18
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - nbconvert=5.5.0
  - nbformat=5.0.8
  - ncurses=6.2
  - notebook=6.4.0
  - openssl=1.1.1k
  - packaging=20.4
  - pandoc=2.11
  - pandocfilters=1.4.2
  - parso=0.8.0
  - pathlib=1.0.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.1.3
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyprojroot=0.2.0
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.6
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2020.1
  - pyzmq=22.0.3
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.1
  - requests=2.24.0
  - send2trash=1.7.1
  - setuptools=49.6.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.36.0
  - terminado=0.10.1
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2020b
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.3.1
  - zlib=1.2.11
  - pip:
    - pyhere==1.0.0